name: main-ci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest   # Choose the runner (GitHub-hosted Ubuntu).
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your code from GitHub.

      - name: Set up JDK 17
        uses: actions/setup-java@v2  # Setup JDK 17 for the job.
        with:
          java-version: '17'   # Use JDK version 17
          distribution: 'adopt'  # Specify the JDK distribution

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build --no-daemon  # Run Gradle build.

      - name: Run Tests
        run: ./gradlew test --no-daemon  # Run Gradle tests and print test names.
        continue-on-error: false

      - name: Upload Test Results
        uses: actions/upload-artifact@v4  # Upload test results as an artifact.
        with:
          name: test-results
          path: build/test-logs/